name: topmost_battery_display
description: "Topmost Battery Display."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.3.1 <4.0.0'

dependencies:
  battery_plus: ^6.0.0
  flutter:
    sdk: flutter
  json_annotation: ^4.8.1
  path_provider: ^2.1.2
  patterns_canvas: ^0.4.0
  tray_manager: ^0.2.1
  url_launcher: ^6.2.5
  window_manager: ^0.3.8

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/
  fonts:
    - family: D-Din
      fonts:
        - asset: assets/d-din.bold.monospaced.otf